apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "orders-app.fullname" . }}
  labels:
    app: {{ template "orders-app.name" . }}
    chart: {{ template "orders-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "orders-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "orders-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SQL_HOST
              value: {{ .Values.config.sql_host | quote }}
            - name: SQL_PORT
              value: {{ .Values.config.sql_port | quote }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/test
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/orders
              port: 3000
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
